# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: web-api

custom:
    secrets: ${file(secrets.json)}

provider:
    name: aws
    region: us-east-2
    runtime: nodejs12.x
    timeout: 30
    stage: ${self:custom.secrets.NODE_ENV}
    environment:
        NODE_ENV: ${self:custom.secrets.NODE_ENV}
        DB_NAME: ${self:custom.secrets.DB_NAME}
        DB_USER: ${self:custom.secrets.DB_USER}
        DB_PASSWORD: ${self:custom.secrets.DB_PASSWORD}
        DB_HOST: ${self:custom.secrets.DB_HOST}
        DB_PORT: ${self:custom.secrets.DB_PORT}
    vpc:
        securityGroupIds:
            - ${self:custom.secrets.SECURITY_GROUP_ID}
        subnetIds:
            - ${self:custom.secrets.SUBNET1_ID}
            - ${self:custom.secrets.SUBNET2_ID}
 
functions:
    hello:
        handler: handler.hello
#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
        events:
            - http:
                path: hello/get
                method: get
    healthCheck:
        handler: handler.healthCheck
        events:
            - http:
                path: healthCheck
                method: post
                cors: true
    create:
        handler: handler.create
        events:
            - http:
                path: user
                method: post
                cors: true
plugins:
    - serverless-offline
